apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: buiquang26/gateway:v1.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
          - name: SERVER_PORT
            value: "8080"
          - name: SERVICE_VEHICLE_URL
            value: "vehicle-service.iot.svc.cluster.local:8081"
          - name: SERVICE_BATTERY_URL
            value: "battery-service.iot.svc.cluster.local:8081"
          - name: SERVICE_SUBSCRIPTION_URL
            value: "subscription-service.iot.svc.cluster.local:8081"
          - name: JHIPSTER_CORS_ALLOWED_ORIGINS
            value: "*"
          - name: JHIPSTER_CORS_ALLOWED_METHODS
            value: "*"
          - name: JHIPSTER_CORS_ALLOWED_HEADERS
            value: "*"
          - name: JHIPSTER_CORS_EXPOSED_HEADERS
            value: "Authorization,Link,X-Total-Count,X-$gatewayApp-alert,X-$gatewayApp-error,X-$gatewayApp-params"
          - name: JHIPSTER_CORS_MAX_AGE
            value: "1800"
          - name: SPRING_JPA_SHOW_SQL
            value: "true"
          - name: SPRING_LIQUIBASE_URL
            value: "jdbc:mysql://34.101.221.224:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
          - name: SPRING_LIQUIBASE_USER
            value: "selex"
          - name: SPRING_LIQUIBASE_PASSWORD
            value: "yq99NPGuUSbHP5bQc7xtdfnvB3qt7WY2"
          - name: SPRING_R2DBC_URL
            value: "r2dbc:mariadb://34.101.221.224:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
          - name: SPRING_R2DBC_USERNAME
            value: "selex"
          - name: SPRING_R2DBC_PASSWORD
            value: "yq99NPGuUSbHP5bQc7xtdfnvB3qt7WY2"
          - name: SPRING_PROFILES_ACTIVE
            value: prod,api-docs
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://admin:${jhipster.registry.password}@jhipster-registry.iot.svc.cluster.local:8761/config
          - name: JHIPSTER_REGISTRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: registry-secret
                key: registry-admin-password
          - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
            value: http://admin:${jhipster.registry.password}@jhipster-registry.iot.svc.cluster.local:8761/eureka/
          - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
            value: "true"
          - name: SPRING_SLEUTH_PROPAGATION_KEYS
            value: "x-request-id,x-ot-span-context"
          - name: JAVA_OPTS
            value: " -Xmx256m -Xms256m"
          - name: SERVER_SHUTDOWN
            value: graceful
        ports:
        - name: http
          containerPort: 8080
