kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m

    receivers:
    - name: alert-emailer
      email_configs:
        - to: 'quangbui010975@gmail.com'
          from: 'qaker1035@gmail.com'
          smarthost: 'smtp.gmail.com:465'
          auth_username: 'qaker1035@gmail.com'
          auth_identity: 'qaker1035@gmail.com'
          auth_password: 'vmsokcociqazwgxs'
          require_tls: false