apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dev-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: mysqldevexporter
  
  template:
    metadata:
      labels:
        app: mysqldevexporter
    
    spec:
      containers:
      - name: mysql-dev-exporter
        image: prom/mysqld-exporter:v0.14.0
        resources:
          limits:
            cpu: 250m
            memory: 180Mi
          requests:
            cpu: 102m
            memory: 180Mi
        env:
          - name: DATA_SOURCE_NAME
            value: selex:yq99NPGuUSbHP5bQc7xtdfnvB3qt7WY2@(34.101.221.224:3306)/
        ports:
        - containerPort: 9104
